M48
; DRILL file KiCad 10.0.0 date 2026-06-25T18:45:14
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-25T18:45:14+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.750
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.988
%
G90
G05
T1
X147.7Y-97.66
X157.86Y-97.66
T2
X152.78Y-97.66
M30
